dmp:
  K: 100
  D: 20
  n_bfs: 1000

  dt: 0.01
  starify: 1
  hull_epsilon: 0.5
  max_compute_time: 1000
  make_convex: 0
  adapt_obstacle_velocity: 0
  crep: 2.5
  reactivity: 1.2
  tail_effect: 0
  convergence_tolerance: 0.01
  dp_decay_rate: 0.5
