
pfmpc_obstacle_constraints:
  # Target generation
  convergence_tolerance: 1.e-3
  rhrp_steps: 24
#  max_compute_time: 10
#  buffer: 1
  # MPC
  ce: 1
  cs: 1.
  R: [0.2, 0.1]
  DR: [0.01, 0.]
  convergence_margin: 0.02

  obs_pen: 1.e+5
  obstacle_padding: 0.05

  #-------- MPC Build params --------- #
  build_mode: 'release'
  integration_method: 'RK4'
  n_pol: 6
  N: 12
  dt: 0.2
  max_No_ell: 10
  N_obs_predict: 12
  max_No_pol: 10
  max_No_vert: 10
  solver_tol: 1.e-5
  solver_max_time: 600 # Maximum duration for mpc solver in milliseconds
  solver_max_inner_iterations: 100
  solver_max_outer_iterations: 10
  solver_initial_tol: 1.e-4
  solver_delta_tol: 1.e-4
  solver_weight_update_factor: 10.0
  solver_initial_penalty: 1000.0
