
pfmpc_artificial_reference:
  rhrp_steps: 24
  # MPC
#  Q: [100, 100, 1]
  R: [0.1, .1]
#  S: [0.01, 0.01]
  S: [0.01, 0.01]
#  T: 1
  K: 0.5
  mu: 5.e+5


  Q: [10, 10, 10]
#  R: [10, 10]
#  R: [0, 10]
  T: 10

  obstacle_padding: 0.0

  #-------- MPC Build params --------- #
  build_mode: 'release'
  integration_method: 'RK4'
  n_pol: 6
  N: 12
  dt: 0.2
  max_No_ell: 10
  N_obs_predict: 12
  max_No_pol: 10
  max_No_vert: 10
  xaeN_con: 0
  dlp_con: 0
  solver_tol: 1.e-5
  solver_max_time: 500 # Maximum duration for mpc solver in milliseconds
  solver_max_inner_iterations: 1000
  solver_max_outer_iterations: 10
  solver_initial_tol: 1.e-4
  solver_delta_tol: 1.e-4
  solver_weight_update_factor: 10.0
  solver_initial_penalty: 1000.0
